MOTIF_DICT = {
    "race": "Competition",
    "beat": "Competition",
    "choose": "Decision",
    "ridicule": "Conflict",
    "mock": "Conflict",
    "win": "Victory",
    "lose": "Defeat",
    "help": "Assistance",
    "attack": "Conflict",
    "escape": "Victory",
    "follow": "Pursuit",
    "promise": "Agreement",
    "teach": "Guidance",
    "deceive": "Trickery",
    "warn": "Conflict",
    "forgive": "Victory",
    "punish": "Justice",
    "trick": "Trickery",
    "betray": "Betrayal",
    "hunt": "Conflict",
    "hide": "Concealment",
    "seek": "Quest",
    "find": "Quest",
    "catch": "Conflict",
    "refuse": "Conflict",
    "enemy": "Conflict",
    "assure": "Trickery",
    "free": "Victory",
    "hostile": "Conflict",
    "plead": "Appeal",
    "entreat": "Appeal",
    "say": "Communication",
    "declare": "Communication",
    "agree": "Victory",
    "reach": "Victory",
    "ate": "Defeat",
    "reply": "Guidance",
    "hunt": "Quest",
    "sting": "Conflict",
    "lost": "Defeat",
    "hire": "Quest",
    "demand": "Conflict",
    "extract": "Victory",
}

CLUSTER_LABELS = {
    0: "Conflict",
    1: "Victory",
    2: "Quest",
    3: "Defeat",
    4: "Appeal",
    5: "Competition",
    6: "Trickery",
    7: "Guidance",
    8: "Communication",
    9: "Appeal"
}